version: "3.3"

volumes:
  foodgram_database:
  foodgram_static:
  foodgram_media:

services:
  database:
    container_name: database
    image: postgres:15.1-alpine
    volumes:
      - foodgram_database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  back:
    container_name: back
    build: ../backend
    restart: always
    volumes:
      - foodgram_static:/foodgram/backend_static/
      - foodgram_media:/foodgram/media/
    depends_on:
      - database
    env_file:
      - ./.env

  front:
    container_name: front
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/backend_static/
      - foodgram_media:/var/html/media/
    depends_on:
      - back
